/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animationproject;

import java.awt.Color;
import javax.swing.Timer;
import javax.swing.SwingUtilities;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import java.awt.BorderLayout;

/**
 *
 * @author LeahMartin
 */
public class frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
        getContentPane().setBackground(Color.white);
        //jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        titleScreen = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        girlTitle = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        walkingToTree = new javax.swing.JPanel();
        walkingGif = new javax.swing.JLabel();
        tree = new javax.swing.JLabel();
        ClickOnTreeText = new javax.swing.JLabel();
        smileReaction = new javax.swing.JPanel();
        Next2 = new javax.swing.JButton();
        smiling = new javax.swing.JLabel();
        GrabPaper = new javax.swing.JPanel();
        GrabPaperGif = new javax.swing.JLabel();
        Next3 = new javax.swing.JButton();
        holdPaper = new javax.swing.JPanel();
        holdingPaper = new javax.swing.JLabel();
        Today = new javax.swing.JLabel();
        Is = new javax.swing.JLabel();
        Windy = new javax.swing.JLabel();
        dotdotdot = new javax.swing.JLabel();
        Next4 = new javax.swing.JButton();
        losePaper = new javax.swing.JPanel();
        losePaperGif = new javax.swing.JLabel();
        OhNoText = new javax.swing.JLabel();
        Next6 = new javax.swing.JButton();
        couponPanel = new javax.swing.JPanel();
        Next5 = new javax.swing.JButton();
        ohNo = new javax.swing.JLabel();
        losePaperReaction = new javax.swing.JPanel();
        losePaperReactionGif = new javax.swing.JLabel();
        iMust = new javax.swing.JLabel();
        findThat = new javax.swing.JLabel();
        coupon = new javax.swing.JLabel();
        Next7 = new javax.swing.JButton();
        floatingPaper = new javax.swing.JPanel();
        floatingPaperGif = new javax.swing.JLabel();
        itsGettingAway = new javax.swing.JLabel();
        Next8 = new javax.swing.JButton();
        paperInWater = new javax.swing.JPanel();
        paperInWaterGifFINAL = new javax.swing.JLabel();
        Next10 = new javax.swing.JButton();
        sadAtBeach = new javax.swing.JPanel();
        sadAtBeachGif = new javax.swing.JLabel();
        Next11 = new javax.swing.JButton();
        smudgedPaper = new javax.swing.JPanel();
        smudgedPaperGif = new javax.swing.JLabel();
        Next12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        excited = new javax.swing.JPanel();
        excitedGif = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Next13 = new javax.swing.JButton();
        theEnd = new javax.swing.JPanel();
        theEndGif = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Start");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleScreen.setBackground(Color.white);

        startButton.setBackground(new java.awt.Color(255, 255, 255));
        startButton.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        startButton.setText("Start!");
        startButton.setBorder(null);
        startButton.setBorderPainted(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        girlTitle.setBackground(new java.awt.Color(255, 255, 255));
        girlTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/girl.gif"))); // NOI18N

        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opening title?.gif"))); // NOI18N

        javax.swing.GroupLayout titleScreenLayout = new javax.swing.GroupLayout(titleScreen);
        titleScreen.setLayout(titleScreenLayout);
        titleScreenLayout.setHorizontalGroup(
            titleScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleScreenLayout.createSequentialGroup()
                .addGroup(titleScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleScreenLayout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(name))
                    .addGroup(titleScreenLayout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(girlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        titleScreenLayout.setVerticalGroup(
            titleScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleScreenLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(titleScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(titleScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(girlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(titleScreenLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        walkingToTree.setBackground(new java.awt.Color(255, 255, 255));
        tree.setVisible(false);

        walkingGif.setVisible(false);
        walkingGif.setBackground(new java.awt.Color(255, 255, 255));
        walkingGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/walking.gif"))); // NOI18N

        tree.setBackground(new java.awt.Color(255, 255, 255));
        tree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FUCKIN THIS IS THE TREE.jpg"))); // NOI18N
        int delay = 170;
        ActionListener taskPerformer = new ActionListener()
        {
            boolean firstTime2 = true;
            int count = 0;
            public void actionPerformed(ActionEvent evt)
            {
                if(firstTime2)
                {
                    if(count == 35)
                    {
                        ClickOnTreeText.setVisible(true);
                        ClickOnTreeText.setForeground(new java.awt.Color(0, 0, 0));
                        //tree.setLocation((tree.getLocation().x+), tree.getLocation().y);
                        firstTime2 = false;
                        ((Timer)evt.getSource()).stop();

                    }

                    tree.setLocation((tree.getLocation().x+10), tree.getLocation().y);
                    System.out.println(SwingUtilities.isEventDispatchThread());

                    count++;
                }
            }
        };
        new Timer(delay, taskPerformer).start();
        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeButton(evt);
            }
        });

        ClickOnTreeText.setForeground(new java.awt.Color(255, 255, 255));
        ClickOnTreeText.setBackground(new java.awt.Color(255, 255, 255));
        ClickOnTreeText.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        ClickOnTreeText.setText("Click on the tree to see  what the paper says!");
        /*int delay2 = 9000;
        ActionListener taskPerformer2 = new ActionListener(){
            int count2 = 0;
            boolean firstTime = true;
            public void actionPerformed(ActionEvent evt)
            {
                if(firstTime)
                {
                    if(count2 == 30)

                    {
                        ((Timer)evt.getSource()).stop();
                        firstTime = false;
                    }

                    count2++;
                }

            }

        };
        new Timer(delay2, taskPerformer2).start();
        */

        javax.swing.GroupLayout walkingToTreeLayout = new javax.swing.GroupLayout(walkingToTree);
        walkingToTree.setLayout(walkingToTreeLayout);
        walkingToTreeLayout.setHorizontalGroup(
            walkingToTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walkingToTreeLayout.createSequentialGroup()
                .addGroup(walkingToTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(walkingToTreeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(walkingGif, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(walkingToTreeLayout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(ClickOnTreeText, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        walkingToTreeLayout.setVerticalGroup(
            walkingToTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(walkingToTreeLayout.createSequentialGroup()
                .addGroup(walkingToTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(walkingToTreeLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(tree))
                    .addComponent(walkingGif, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ClickOnTreeText)
                .addContainerGap(647, Short.MAX_VALUE))
        );

        smileReaction.setBackground(new java.awt.Color(255, 255, 255));

        Next2.setBackground(new java.awt.Color(255, 255, 255));
        Next2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next2.setText("Next");
        Next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next2ActionPerformed(evt);
            }
        });

        smiling.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smileFINAL.gif"))); // NOI18N

        javax.swing.GroupLayout smileReactionLayout = new javax.swing.GroupLayout(smileReaction);
        smileReaction.setLayout(smileReactionLayout);
        smileReactionLayout.setHorizontalGroup(
            smileReactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smileReactionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(smiling, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Next2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        smileReactionLayout.setVerticalGroup(
            smileReactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smileReactionLayout.createSequentialGroup()
                .addGroup(smileReactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smileReactionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(smiling, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smileReactionLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(Next2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(523, Short.MAX_VALUE))
        );

        GrabPaper.setBackground(new java.awt.Color(255, 255, 255));

        GrabPaperGif.setBackground(new java.awt.Color(255, 255, 255));
        GrabPaperGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/takePaper.gif"))); // NOI18N

        Next3.setBackground(new java.awt.Color(255, 255, 255));
        Next3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next3.setText("Next");
        Next3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GrabPaperLayout = new javax.swing.GroupLayout(GrabPaper);
        GrabPaper.setLayout(GrabPaperLayout);
        GrabPaperLayout.setHorizontalGroup(
            GrabPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrabPaperLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(GrabPaperGif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Next3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        GrabPaperLayout.setVerticalGroup(
            GrabPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrabPaperLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(Next3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GrabPaperLayout.createSequentialGroup()
                .addComponent(GrabPaperGif, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 531, Short.MAX_VALUE))
        );

        holdPaper.setBackground(new java.awt.Color(255, 255, 255));
        holdPaper.setVisible(false);

        holdingPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/windPaper.gif"))); // NOI18N

        Today.setBackground(new java.awt.Color(255, 255, 255));
        Today.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Today.setText("Today");

        Is.setBackground(new java.awt.Color(255, 255, 255));
        Is.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Is.setText("is");

        Windy.setBackground(new java.awt.Color(255, 255, 255));
        Windy.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Windy.setText("Windy");

        dotdotdot.setBackground(new java.awt.Color(255, 255, 255));
        dotdotdot.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        dotdotdot.setText("...");

        Next4.setBackground(new java.awt.Color(255, 255, 255));
        Next4.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next4.setText("Next");
        Next4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout holdPaperLayout = new javax.swing.GroupLayout(holdPaper);
        holdPaper.setLayout(holdPaperLayout);
        holdPaperLayout.setHorizontalGroup(
            holdPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(holdPaperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(holdingPaper)
                .addGap(35, 35, 35)
                .addGroup(holdPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Today, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Is, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(holdPaperLayout.createSequentialGroup()
                        .addComponent(Windy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dotdotdot))
                    .addComponent(Next4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        holdPaperLayout.setVerticalGroup(
            holdPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(holdPaperLayout.createSequentialGroup()
                .addGroup(holdPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(holdPaperLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(Today, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Is, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(holdPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Windy)
                            .addComponent(dotdotdot))
                        .addGap(35, 35, 35)
                        .addComponent(Next4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(holdPaperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(holdingPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        losePaper.setBackground(new java.awt.Color(255, 255, 255));

        losePaperGif.setBackground(new java.awt.Color(255, 255, 255));
        losePaperGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/losePaper.gif"))); // NOI18N

        OhNoText.setBackground(new java.awt.Color(255, 255, 255));
        OhNoText.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        OhNoText.setText("Oh no!");

        Next6.setBackground(new java.awt.Color(255, 255, 255));
        Next6.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next6.setText("Next");
        Next6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout losePaperLayout = new javax.swing.GroupLayout(losePaper);
        losePaper.setLayout(losePaperLayout);
        losePaperLayout.setHorizontalGroup(
            losePaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(losePaperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(losePaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OhNoText)
                    .addComponent(Next6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(losePaperGif, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        losePaperLayout.setVerticalGroup(
            losePaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(losePaperLayout.createSequentialGroup()
                .addGroup(losePaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(losePaperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(losePaperGif, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(losePaperLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(OhNoText)
                        .addGap(53, 53, 53)
                        .addComponent(Next6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        couponPanel.setBackground(new java.awt.Color(255, 255, 255));

        Next5.setBackground(new java.awt.Color(255, 255, 255));
        Next5.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next5.setText("Next");
        Next5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next5ActionPerformed(evt);
            }
        });

        ohNo.setBackground(new java.awt.Color(255, 255, 255));
        ohNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paper on tree.jpg"))); // NOI18N

        javax.swing.GroupLayout couponPanelLayout = new javax.swing.GroupLayout(couponPanel);
        couponPanel.setLayout(couponPanelLayout);
        couponPanelLayout.setHorizontalGroup(
            couponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(couponPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ohNo)
                .addGap(18, 18, 18)
                .addComponent(Next5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        couponPanelLayout.setVerticalGroup(
            couponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(couponPanelLayout.createSequentialGroup()
                .addGroup(couponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(couponPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ohNo, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(couponPanelLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(Next5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(400, Short.MAX_VALUE))
        );

        losePaperReaction.setBackground(new java.awt.Color(255, 255, 255));

        losePaperReactionGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/losePaperReaction.gif"))); // NOI18N

        iMust.setBackground(new java.awt.Color(255, 255, 255));
        iMust.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        iMust.setText("I must");

        findThat.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        findThat.setText("find that");

        coupon.setBackground(new java.awt.Color(255, 255, 255));
        coupon.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 48)); // NOI18N
        coupon.setText("coupon!");

        Next7.setBackground(new java.awt.Color(255, 255, 255));
        Next7.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next7.setText("Next");
        Next7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout losePaperReactionLayout = new javax.swing.GroupLayout(losePaperReaction);
        losePaperReaction.setLayout(losePaperReactionLayout);
        losePaperReactionLayout.setHorizontalGroup(
            losePaperReactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(losePaperReactionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(losePaperReactionGif, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(losePaperReactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(losePaperReactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(coupon)
                        .addGroup(losePaperReactionLayout.createSequentialGroup()
                            .addComponent(iMust)
                            .addGap(66, 66, 66))
                        .addComponent(Next7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(findThat))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        losePaperReactionLayout.setVerticalGroup(
            losePaperReactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(losePaperReactionLayout.createSequentialGroup()
                .addComponent(losePaperReactionGif, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(losePaperReactionLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(iMust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(findThat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coupon)
                .addGap(66, 66, 66)
                .addComponent(Next7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        floatingPaper.setBackground(new java.awt.Color(255, 255, 255));

        floatingPaperGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flyingPaper.gif"))); // NOI18N

        itsGettingAway.setBackground(new java.awt.Color(255, 255, 255));
        itsGettingAway.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 48)); // NOI18N
        itsGettingAway.setText("It's getting away... ");

        Next8.setBackground(new java.awt.Color(255, 255, 255));
        Next8.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next8.setText("Next");
        Next8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout floatingPaperLayout = new javax.swing.GroupLayout(floatingPaper);
        floatingPaper.setLayout(floatingPaperLayout);
        floatingPaperLayout.setHorizontalGroup(
            floatingPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floatingPaperLayout.createSequentialGroup()
                .addComponent(floatingPaperGif, javax.swing.GroupLayout.PREFERRED_SIZE, 1314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(floatingPaperLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(itsGettingAway, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Next8, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        floatingPaperLayout.setVerticalGroup(
            floatingPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floatingPaperLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(floatingPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itsGettingAway)
                    .addComponent(Next8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addComponent(floatingPaperGif, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paperInWater.setBackground(new java.awt.Color(255, 255, 255));

        paperInWaterGifFINAL.setBackground(new java.awt.Color(255, 255, 255));
        paperInWaterGifFINAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paperInWaterFINAL.gif"))); // NOI18N

        Next10.setBackground(new java.awt.Color(255, 255, 255));
        Next10.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next10.setText("Next");
        Next10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paperInWaterLayout = new javax.swing.GroupLayout(paperInWater);
        paperInWater.setLayout(paperInWaterLayout);
        paperInWaterLayout.setHorizontalGroup(
            paperInWaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paperInWaterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Next10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paperInWaterGifFINAL)
                .addGap(213, 213, 213))
        );
        paperInWaterLayout.setVerticalGroup(
            paperInWaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paperInWaterLayout.createSequentialGroup()
                .addGroup(paperInWaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paperInWaterLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(Next10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paperInWaterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paperInWaterGifFINAL, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(421, Short.MAX_VALUE))
        );

        sadAtBeach.setBackground(new java.awt.Color(255, 255, 255));

        sadAtBeachGif.setBackground(new java.awt.Color(255, 255, 255));
        sadAtBeachGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sadAtBeach.gif"))); // NOI18N

        Next11.setBackground(new java.awt.Color(255, 255, 255));
        Next11.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next11.setText("Next");
        Next11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sadAtBeachLayout = new javax.swing.GroupLayout(sadAtBeach);
        sadAtBeach.setLayout(sadAtBeachLayout);
        sadAtBeachLayout.setHorizontalGroup(
            sadAtBeachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sadAtBeachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sadAtBeachGif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Next11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sadAtBeachLayout.setVerticalGroup(
            sadAtBeachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sadAtBeachLayout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addComponent(Next11)
                .addGap(277, 277, 277))
            .addComponent(sadAtBeachGif, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        smudgedPaper.setBackground(new java.awt.Color(255, 255, 255));

        smudgedPaperGif.setBackground(new java.awt.Color(255, 255, 255));
        smudgedPaperGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blurredPaper.jpg"))); // NOI18N

        Next12.setBackground(new java.awt.Color(255, 255, 255));
        Next12.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next12.setText("Next");
        Next12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next12ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        jLabel1.setText("The paper is ruined, ");

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        jLabel2.setText("but I can still see");

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        jLabel3.setText("the address!");

        javax.swing.GroupLayout smudgedPaperLayout = new javax.swing.GroupLayout(smudgedPaper);
        smudgedPaper.setLayout(smudgedPaperLayout);
        smudgedPaperLayout.setHorizontalGroup(
            smudgedPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smudgedPaperLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(smudgedPaperGif, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(smudgedPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Next12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        smudgedPaperLayout.setVerticalGroup(
            smudgedPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smudgedPaperLayout.createSequentialGroup()
                .addGroup(smudgedPaperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smudgedPaperLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(67, 67, 67)
                        .addComponent(Next12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(smudgedPaperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(smudgedPaperGif, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        excited.setBackground(new java.awt.Color(255, 255, 255));

        excitedGif.setBackground(new java.awt.Color(255, 255, 255));
        excitedGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/excited.gif"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        jLabel4.setText("Let's go!");

        Next13.setBackground(new java.awt.Color(255, 255, 255));
        Next13.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 36)); // NOI18N
        Next13.setText("Next");
        Next13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout excitedLayout = new javax.swing.GroupLayout(excited);
        excited.setLayout(excitedLayout);
        excitedLayout.setHorizontalGroup(
            excitedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excitedLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(excitedGif, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(excitedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Next13, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        excitedLayout.setVerticalGroup(
            excitedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(excitedLayout.createSequentialGroup()
                .addGroup(excitedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(excitedLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(excitedGif, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(excitedLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Next13, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        theEnd.setBackground(new java.awt.Color(255, 255, 255));

        theEndGif.setBackground(new java.awt.Color(255, 255, 255));
        theEndGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theEnd.gif"))); // NOI18N

        javax.swing.GroupLayout theEndLayout = new javax.swing.GroupLayout(theEnd);
        theEnd.setLayout(theEndLayout);
        theEndLayout.setHorizontalGroup(
            theEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theEndLayout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(theEndGif, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(824, Short.MAX_VALUE))
        );
        theEndLayout.setVerticalGroup(
            theEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theEndLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(theEndGif, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(walkingToTree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(couponPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(smileReaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(GrabPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(holdPaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(losePaperReaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sadAtBeach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(losePaper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(floatingPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(paperInWater, javax.swing.GroupLayout.PREFERRED_SIZE, 1177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(398, 398, 398)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(theEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(excited, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(smudgedPaper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(walkingToTree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(couponPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(smileReaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(GrabPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(holdPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(losePaperReaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(sadAtBeach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(losePaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(floatingPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paperInWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1363, 1363, 1363)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(smudgedPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(excited, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(theEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(944, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
       name.setVisible(false);
       girlTitle.setVisible(false);
       startButton.setVisible(false);
       titleScreen.setVisible(false);
       walkingToTree.setVisible(true);
       walkingGif.setVisible(true);
       tree.setVisible(true);
       ClickOnTreeText.setVisible(true);
       couponPanel.setVisible(false);
       ohNo.setVisible(false);
       smileReaction.setVisible(false);
       smiling.setVisible(false);
       //holdPaper.setVisible(false);
       //holdingPaper.setVisible(false);
       //System.out.println(walkingToTree.isVisible());
       //System.out.println(holdingPaper.isVisible());
       holdPaper.setSize(-50,-50);
       holdingPaper.setSize(-50,-50);
       losePaperReaction.setVisible(false);
       losePaperReactionGif.setVisible(false);
       paperInWater.setVisible(false);
       paperInWaterGifFINAL.setVisible(false);
       //itsGettingAway.setVisible(false);
       floatingPaper.setVisible(false);
       floatingPaperGif.setVisible(false);
       sadAtBeach.setVisible(false);
        sadAtBeachGif.setVisible(false);
        smudgedPaper.setVisible(false);
        smudgedPaperGif.setVisible(false);
        //happyAnais.setVisible(false);
        //happyAnaisGif.setVisible(false);
        //jPanel3.setVisible(false);
        //jLabel1.setVisible(false);
        excited.setVisible(false);
        excitedGif.setVisible(false);
       theEnd.setVisible(false);
        theEndGif.setVisible(false);
      

       //jLabel2.setVisible(true);
       
      
    }//GEN-LAST:event_startButtonActionPerformed

    private void treeButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeButton
       // TODO add your handling code here:
      
       walkingGif.setVisible(false);
       tree.setVisible(false);
       ClickOnTreeText.setVisible(false);
       walkingToTree.setVisible(false);
       couponPanel.setVisible(true);
        ohNo.setVisible(true);
    }//GEN-LAST:event_treeButton

    private void Next5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next5ActionPerformed
           // TODO add your handling code here:
      couponPanel.setVisible(false);
       ohNo.setVisible(false);
       smileReaction.setVisible(true);
       smiling.setVisible(true);
    }//GEN-LAST:event_Next5ActionPerformed

    private void Next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next2ActionPerformed
        // TODO add your handling code here:
        smileReaction.setVisible(false);
        smiling.setVisible(false);
        GrabPaper.setVisible(true);
        GrabPaperGif.setVisible(true);
        holdPaper.setVisible(false);
        holdingPaper.setVisible(false);
    }//GEN-LAST:event_Next2ActionPerformed

    private void Next3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next3ActionPerformed
        // TODO add your handling code here:
         GrabPaper.setVisible(false);
         GrabPaperGif.setVisible(false);
         holdPaper.setVisible(true);
         holdingPaper.setVisible(true);
         holdPaper.setSize(100,100);
       holdingPaper.setSize(100,100);
       losePaper.setVisible(false);
       losePaperGif.setVisible(false);
       
    }//GEN-LAST:event_Next3ActionPerformed

    private void Next4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next4ActionPerformed
        // TODO add your handling code here:
        losePaper.setVisible(true);
        losePaperGif.setVisible(true);
        holdPaper.setVisible(false);
        holdingPaper.setVisible(false);
        OhNoText.setVisible(true);
    }//GEN-LAST:event_Next4ActionPerformed

    private void Next6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next6ActionPerformed
        // TODO add your handling code here:
        losePaperReaction.setVisible(true);
        losePaperReactionGif.setVisible(true);
        losePaper.setVisible(false);
        losePaperGif.setVisible(false);
         OhNoText.setVisible(false);
    }//GEN-LAST:event_Next6ActionPerformed

    private void Next7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next7ActionPerformed
        // TODO add your handling code here:
        floatingPaper.setVisible(true);
        floatingPaperGif.setVisible(true);
        losePaperReaction.setVisible(false);
        losePaperReactionGif.setVisible(false);
        iMust.setVisible(false);
        findThat.setVisible(false);
        coupon.setVisible(false);
    }//GEN-LAST:event_Next7ActionPerformed

    private void Next8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next8ActionPerformed
        // TODO add your handling code here:
        itsGettingAway.setVisible(false);
        floatingPaper.setVisible(false);
        floatingPaperGif.setVisible(false);
        paperInWater.setVisible(true);
        paperInWaterGifFINAL.setVisible(true);
        System.out.println(sadAtBeach.getSize(null));
    }//GEN-LAST:event_Next8ActionPerformed

    private void Next10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next10ActionPerformed
        // TODO add your handling code here:
        
        sadAtBeach.setVisible(true);
        sadAtBeachGif.setVisible(true);
        paperInWater.setVisible(false);
        paperInWaterGifFINAL.setVisible(false);
        revalidate();
        repaint();
        pack();
        
    }//GEN-LAST:event_Next10ActionPerformed

    private void Next11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next11ActionPerformed
        // TODO add your handling code here:
        sadAtBeach.setVisible(false);
        sadAtBeachGif.setVisible(false);
        smudgedPaper.setVisible(true);
        smudgedPaperGif.setVisible(true);
        GroupLayout layout = (GroupLayout) getContentPane().getLayout();      
        layout.replace(sadAtBeach, smudgedPaper);
        
        
        
    }//GEN-LAST:event_Next11ActionPerformed

    private void Next12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next12ActionPerformed
        // TODO add your handling code here:
        smudgedPaper.setVisible(false);
        smudgedPaperGif.setVisible(false);
        excited.setVisible(true);
        excitedGif.setVisible(true);
        GroupLayout layout = (GroupLayout) getContentPane().getLayout(); 
        System.out.println(smudgedPaper);
        System.out.println(excited);
        getContentPane().removeAll(); 
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(excited);
        //layout.replace(smudgedPaper, excited);
        validate();
        
    }//GEN-LAST:event_Next12ActionPerformed

    private void Next13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next13ActionPerformed
        // TODO add your handling code here:
         excited.setVisible(false);
        excitedGif.setVisible(false);
        theEnd.setVisible(true);
        theEndGif.setVisible(true);
        //GroupLayout layout = (GroupLayout) getContentPane().getLayout(); 
        //System.out.println(excited);
        //System.out.println(theEnd);
        getContentPane().removeAll(); 
        //getContentPane().setLayout(new BorderLayout());
        getContentPane().add(theEnd);
        //layout.replace(smudgedPaper, excited);
        validate();
        
    }//GEN-LAST:event_Next13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClickOnTreeText;
    private javax.swing.JPanel GrabPaper;
    private javax.swing.JLabel GrabPaperGif;
    private javax.swing.JLabel Is;
    private javax.swing.JButton Next10;
    private javax.swing.JButton Next11;
    private javax.swing.JButton Next12;
    private javax.swing.JButton Next13;
    private javax.swing.JButton Next2;
    private javax.swing.JButton Next3;
    private javax.swing.JButton Next4;
    private javax.swing.JButton Next5;
    private javax.swing.JButton Next6;
    private javax.swing.JButton Next7;
    private javax.swing.JButton Next8;
    private javax.swing.JLabel OhNoText;
    private javax.swing.JLabel Today;
    private javax.swing.JLabel Windy;
    private javax.swing.JLabel coupon;
    private javax.swing.JPanel couponPanel;
    private javax.swing.JLabel dotdotdot;
    private javax.swing.JPanel excited;
    private javax.swing.JLabel excitedGif;
    private javax.swing.JLabel findThat;
    private javax.swing.JPanel floatingPaper;
    private javax.swing.JLabel floatingPaperGif;
    private javax.swing.JLabel girlTitle;
    private javax.swing.JPanel holdPaper;
    private javax.swing.JLabel holdingPaper;
    private javax.swing.JLabel iMust;
    private javax.swing.JLabel itsGettingAway;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel losePaper;
    private javax.swing.JLabel losePaperGif;
    private javax.swing.JPanel losePaperReaction;
    private javax.swing.JLabel losePaperReactionGif;
    private javax.swing.JLabel name;
    private javax.swing.JLabel ohNo;
    private javax.swing.JPanel paperInWater;
    private javax.swing.JLabel paperInWaterGifFINAL;
    private javax.swing.JPanel sadAtBeach;
    private javax.swing.JLabel sadAtBeachGif;
    private javax.swing.JPanel smileReaction;
    private javax.swing.JLabel smiling;
    private javax.swing.JPanel smudgedPaper;
    private javax.swing.JLabel smudgedPaperGif;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel theEnd;
    private javax.swing.JLabel theEndGif;
    private javax.swing.JPanel titleScreen;
    private javax.swing.JLabel tree;
    private javax.swing.JLabel walkingGif;
    private javax.swing.JPanel walkingToTree;
    // End of variables declaration//GEN-END:variables
}
